FROM ubuntu:22.04

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
        build-essential cmake git \
        libavcodec-dev libavformat-dev libswresample-dev libswscale-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY . /app

RUN cmake -S . -B /build -DCMAKE_BUILD_TYPE=Release && \
    cmake --build /build --parallel

CMD ["/bin/bash"]
